version: '3.9'

services:
  postgres:
    image: postgres:17.2
    container_name: book_list_db
    environment:
      POSTGRES_DB: book_list_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ~/pgdata:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tomcat:
    image: tomcat:9.0
    container_name: book_list_tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/your-app-name.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - postgres
