CREATE DATABASE books_list_db;
       CREATE TABLE books_list(
       id INT GENERATED BY DEFAULT AS IDENTITY,
       vendorCode VARCHAR(100) NOT NULL DEFAULT 'Неизвестен',
       title VARCHAR (100) UNIQUE NOT NULL,
       year INT NOT NULL,
       brand VARCHAR (100),
       stock INT,
       price INT NOT NULL
);
